models:
    yoloONNX_weight: "./weights/best2.onnx"
    yoloONNX_classify: "./weights/best_staff_customer_vtt.onnx"
cameras:
  0:
    rtsp_url: "rtsp://admin:eidox2026@293pvdcam1.cameraddns.net:5554/live"
    box_id: "2e5e8861-75ed-4c5a-b6ec-ddb89b04e8c7"
    cam_id: "17052f6b-00a0-4562-9574-5d291b5fd6de"
    zone_id: "550e8400-e29b-41d4-a716-446655440000"
    max_person: 12  # Mức độ cảnh báo
    kafka_interval: 5 # Thời gian gửi mess tiếp
    current_frame : 0
    zone_1: [[0.76, 0.14], [0.49, 0.02], [0.48, 0.41], [0.69, 0.7]]
    zone_2: [[0.46, 1.0], [0.55, 0.69], [0.29, 0.57], [0.09, 0.9], [0.14, 1.0]]
    zone_3: [[0.67, 0.09], [0.46, 0.09], [0.36, 0.2], [0.39, 0.36], [0.45, 0.36], [0.5, 0.28], [0.67, 0.27]]  
 
kafka:
  broker: "gateway-1.hn.eidox.ai:9093"
  topic: "gateway-box-pchm"
  client_id: "python-producer"

  security:
    protocol: "PLAINTEXT"
    # protocol: "SSL"
    # ca_location: "./cert/ca-root.pem"
    # cert_location: "./cert/ca-cert.pem"
    # key_location: "./cert/ca-key.pem"

  retries: 5
  retry_backoff_ms: 1000